name: Building
on: [ workflow_dispatch, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        abi: [ armeabi-v7a, arm64-v8a ]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Setup the environment
        run: |
          sudo apt update
          sudo apt install meson nasm ninja-build

      - name: Start building
        run: |
          export ANDROID_SDK_HOME=$ANDROID_HOME
          export ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME
          ./ffmpeg-android-maker.sh --enable-libaom --enable-libvpx --enable-libx264 --enable-libx265 --android-api-level=24 -abis=${{ matrix.abi }}

      - name: Upload Temporary ABI Artifact
        uses: actions/upload-artifact@v7
        with:
          name: temp-libs-${{ matrix.abi }}
          path: output/

  merge_and_zip:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
    
      - name: Download All Temporary Artifacts
        uses: actions/download-artifact@v6
        with:
          pattern: temp-libs-*
          path: temp_download

      - name: Restructure Folders
        run: |
          mkdir -p final_output/armeabi-v7a
          mkdir -p final_output/arm64-v8a
          mv temp_download/temp-libs-armeabi-v7a/lib/armeabi-v7a final_output/armeabi-v7a/lib
          mv temp_download/temp-libs-armeabi-v7a/include/armeabi-v7a final_output/armeabi-v7a/include
          mv temp_download/temp-libs-arm64-v8a/lib/arm64-v8a final_output/arm64-v8a/lib
          mv temp_download/temp-libs-arm64-v8a/include/arm64-v8a final_output/arm64-v8a/include

      - name: Upload Combined Zip
        uses: actions/upload-artifact@v7
        with:
          name: libs
          path: final_output/

      - name: Delete Temporary Artifacts
        uses: geekyeggo/delete-artifact@v6
        with:
          name: |
            temp-libs-armeabi-v7a
            temp-libs-arm64-v8a
