name: Compiling shit
on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        abi: [ "armeabi-v7a", "arm64-v8a" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Setup the environment
        run: |
          sudo apt update
          sudo apt install -y meson nasm ninja-build

      - name: Executing the script
        run: |
          chmod +x ffmpeg-android-maker.sh
          export ANDROID_SDK_HOME=$ANDROID_HOME
          export ANDROID_NDK_HOME=$ANDROID_NDK_ROOT
          ./ffmpeg-android-maker.sh \
            --target-abis=${{ matrix.abi }} \
            --enable-libaom \
            --enable-libvpx \
            --enable-libx264 \
            --enable-libx265 \
            --android-api-level=24

      - name: Upload ABI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-${{ matrix.abi }}
          path: output/

  bundle:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Download all compiled architectures
        uses: actions/download-artifact@v4
        with:
          path: ffmpeg-libraries

      - name: Bundle into single download
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-android-arm-libs
          path: ffmpeg-libraries/
